apiVersion: v1
kind: Template
metadata:
  name: ocp-demo-spring-pet-clinic-template

objects:
  # Service
  # Acts as a reverse proxy for our Pods. Adds/removes pods as needed to the service based on labels.
  - kind: Service
    apiVersion: v1
    metadata:
      name: "ocp-demo-spring-pet-clinic"
      labels:
        app: "ocp-demo-spring-pet-clinic"
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: "ocp-demo-spring-pet-clinic"
        deploymentconfig: "ocp-demo-spring-pet-clinic"
      sessionAffinity: None

  # Route
  # Exposes the service to a particular endpoint DNS
  - kind: Route
    apiVersion: v1
    metadata:
      name: "ocp-demo-spring-pet-clinic"
      namespace: "ocp-demo"
      labels:
        app: "ocp-demo-spring-pet-clinic"
    spec:
      host: "ocp-demo-spring-pet-clinic.127.0.0.1.nip.io"
      to:
        kind: Service
        name: "ocp-demo-spring-pet-clinic"
        weight: 100
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None

  # ImageStream
  # Performs automated actions based on one or more docker image tags
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "ocp-demo-spring-pet-clinic"
      namespace: "ocp-demo"
    spec:
      dockerImageRepository: "stricklerxc/demo:latest"
      tags:
        -
          name: latest
          from:
            kind: DockerImage
            name: "stricklerxc/demo:latest"
      importPolicy:
        insecure: true

  # Deployment
  # Configures when and how deployments of the app take place
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "ocp-demo-spring-pet-clinic"
      namespace: "ocp-demo"
      labels:
        app: "ocp-demo-spring-pet-clinic"
    spec:
      replicas: 1
      selector:
        app: "ocp-demo-spring-pet-clinic"
        deploymentconfig: "ocp-demo-spring-pet-clinic"
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: "ocp-demo-spring-pet-clinic"
            deploymentconfig: "ocp-demo-spring-pet-clinic"
        spec:
          containers:
            - name: "ocp-demo-spring-pet-clinic"
              image: "stricklerxc/demo:latest"
              ports:
                - containerPort: 8080
                  protocol: TCP
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "2"
                  memory: 2Gi
                requests:
                  cpu: 250m
                  memory: 768Mi
        triggers:
          - type: ConfigChange
          - type: ImageChange
            imageChangeParams:
              automatic: true
              containerNames:
                - "ocp-demo-spring-pet-clinic"
              from:
                kind: ImageStreamTag
                namespace: "ocp-demo"
                name: "ocp-demo-spring-pet-clinic:latest"
